services:
  - type: web
    name: bitcode-api
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: MONGO_URI
        value: mongodb+srv://deepakkaligotla:XfRcLu53HRWvMR6W@cluster.mongodb.net/BitCode-APIs?retryWrites=true&w=majority